name: huawei_account_example
description: Demonstrates how to use the Huawei Account plugin.
version: 5.2.0+300

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_account:
    path: ../

  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
