name: huawei_health_example
description: Demonstrates how to use the HUAWEI Health Kit Plugin.
version: 5.0.5+301

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_health:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true