name: huawei_gameservice
description: HUAWEI Game Service, provides a range of development capabilities to help you develop your games more efficiently.
version: 5.0.4+303
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-gameservice

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.gameservice
        pluginClass: HuaweiGameServicePlugin
