name: huawei_ads
description: HUAWEI Ads Kit plugin for Flutter utilizes Huawei's vast user base and extensive data capabilities to deliver targeted, high quality ad content to users.
version: 13.4.35+301
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-ads

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.ads
        pluginClass: HmsAdsPlugin

