name: huawei_ml_example
description: Demonstrates how to use the Huawei ML plugin.
version: 2.0.5+301

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_ml:
    path: ../
  image_picker: ^0.6.7+4
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.11
  file_picker: ^1.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/asr.png
    - assets/bcr.png
    - assets/class.png
    - assets/doc.png
    - assets/face.png
    - assets/gcr.png
    - assets/handkey.png
    - assets/icr.png
    - assets/isr.png
    - assets/landmark.png
    - assets/langdetect.png
    - assets/liveness.png
    - assets/ml.png
    - assets/model.png
    - assets/object.png
    - assets/productsegment.png
    - assets/rtt.png
    - assets/scene.png
    - assets/segmentation.png
    - assets/skeleton.png
    - assets/sounddetect.png
    - assets/text.png
    - assets/textembed.png
    - assets/tisr.png
    - assets/trans.png
    - assets/tts.png