name: huawei_dtm
description: Huawei DTM Kit plugin for Flutter. With Huawei DTM Kit, you can dynamically update tracking tags to track
  specific events and report data to third-party analytics platforms.
version: 5.0.4+302
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-dtm

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.dtm
        pluginClass: DTMPlugin

