name: huawei_wallet_example
description: Demonstrates how to use the huawei_wallet plugin.
version: 4.0.4+302

publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_wallet:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
