name: huawei_wallet
description: HUAWEI Wallet Kit provides easy-to-access digital passes such as cards, coupons etc. on an integrated platform.
version: 4.0.4+302
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-wallet

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.wallet
        pluginClass: HuaweiWalletPlugin
