name: huawei_site_example
description: Demonstrates how to use the Huawei Site plugin.
version: 5.1.0+301

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_site:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
