name: huawei_contactshield_example
description: Demonstrates how to use the Huawei Contact Shield plugin.
version: 5.1.0+301

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.13.3

  huawei_contactshield:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
