name: huawei_gameservice_example
description: Demonstrates how to use the Flutter HUAWEI Game Service plugin.
version: 5.0.4+303

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_account: 5.0.3+303
  huawei_gameservice:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/HMSIcons/
